apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redfish_exporter.fullname" . }}
  labels:
    {{- include "redfish_exporter.labels" . | nindent 4 }}
stringData:
  redfish_exporter.yml: |
    {{- .Values.exporterConfig | toYaml | nindent 4 }}