name: build redfish exporter package

on: 
  issue_comment:
    types:
    - edited
    - created
  pull_request:
    branches:
    - master

jobs:
  centos-7:
    name: on centos 7
    runs-on: ubuntu-20.04
    if: github.event.comment.body == 'build on centos 7'  || github.event.pull_request.opened || github.event.pull_request.reopened
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
#      - name: scan codeql
#        uses: github/codeql-action/init@v1
#        with:
#          languages: go
      - name: Update apt repository
        run: sudo apt-get update -y
      - name: Install dependencies
        run: sudo apt-get install -y make curl podman
      - name: build package
        run: make docker-build-centos7
  centos-8:
    name: on centos 8
    runs-on: ubuntu-20.04
    if: github.event.comment.body == 'build on centos 8' || github.event.pull_request.opened || github.event.pull_request.reopened
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
#      - name: scan codeql
#        uses: github/codeql-action/init@v1
#        with:
#          languages: go
      - name: Update apt repository
        run: sudo apt-get update -y
      - name: Install dependencies
        run: sudo apt-get install -y make curl podman
      - name: build package
        run: make docker-build-centos8
